# -*- coding: utf-8 -*-
"""230227_voicevox.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11C6-F6YMg5dIIpywssX0kwehdMcQr594
"""

# Commented out IPython magic to ensure Python compatibility.

from datetime import datetime
for i in range(5):
    print(f'【{datetime.now()}】: Pythonで出力！')
    
#初期設定（2023/07/24修正）
!curl -sSfL https://raw.githubusercontent.com/VOICEVOX/voicevox_core/8cf307df4412dc0db0b03c6957b83b032770c31a/scripts/downloads/download.sh | bash -s
# %cd voicevox_core/
!wget https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.1/voicevox_core-0.14.1+cpu-cp38-abi3-linux_x86_64.whl
!pip install voicevox_core-0.14.1+cpu-cp38-abi3-linux_x86_64.whl
!wget https://raw.githubusercontent.com/VOICEVOX/voicevox_core/406f6c41408836840b9a38489d0f670fb960f412/example/python/run.py

#実行（2023/06/15修正）
text = 'どうも、クラゲジュニアです。よろしくね'
speaker_id = 0

!python ./run.py --dict-dir "./open_jtalk_dic_utf_8-1.11" --text $text --out "../data.wav" --speaker-id $speaker_id
from IPython.display import Audio
Audio('../data.wav')
